development:
  adapter: mysql2
  database: person_management
  username: root
  password: 123456
  host: localhost
test:
  adapter: mysql2
  database: person_management_test
  username: root
  password: 123456
  host: localhost
production:
  adapter: mysql2
  database: person_management
  username: root
  password: 123456
  host: localhost
